version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/mern-starter
    steps:
      - checkout
      - run: |
          pwd
          ls
          git branch
