version: 2
jobs:
    build:
        docker:
            - image: circleci/python:2.7-stretch-browsers
        steps:
            - checkout
            - run: |
                git status
                git remote -v
                cd ..
                pwd
                ls
                
